### ISSUE TITLE
Lab 5 Table of Contents Doesn't knit properly

### ISSUE THREAD

**Issue by jnelson7** [dblodgett-usgs/NWCEd#21]
For some reason the new "Exercise 2" and "Try It Yourself" headers don't show up in the table of contents. After doing some testing, it appears that somewhere just before the "Step 3" header things start breaking.  Do you have any ideas as to why this might be happening?

Thanks!

**Comment by dblodgett-usgs** [comment]
The only thing I see is that there is no line above the `## Exercise 2` line. I doubt that's it. Not sure without knitting it miyself, don't have time now.
